export const miojoMainQuote = 'Mussum Ipsum, cacilds vidis litro abertis.'

export const miojoQuotes = [
  'Para nao ficar muito cansativo vou agora ensinar a fazer um belo miojo.',
  'Ferva trezentos ml de agua em uma panela.',
  'Quando estiver fervendo coloque o miojo.',
  'Espere cozinhar por tres minutos.',
  'Retire o mijo do fogao.',
  'Coloque o tempero,misture bem e sirva.',
  'Coloque duas xícaras e meia de água em uma tigela e coloque o miojo dentro.',
  'Leve ao micro-ondas, ligue de 3 a 5 minutos.',
  'Quando terminar coloque o tempero e mexa bem, sirva.',
  'Primeiro cozinhe as salsichas por 10 minutos em água que fique um pouco acima delas.',
  'Quando terminar de cozinhar escorra a água e pique as salsichas.',
  'Coloque água novamente e cozinhe o miojo.',
  'Quando terminar acrescente queijo ralado, o tempero e mexa bem.',
  'Em uma panela coloque o chuchu, batata e a cenoura e cozinhe por 10 minutos.',
  'Acrescente o miojo e deixe cozinhar por mais alguns minutos.',
  'Quando terminar o cozimento, acrescente o restante dos ingredientes e pronto.',
  'Prepare o seu miojo, cozinhando com os ovos.',
  'Após cozido, coloque a lata de ervilha, despeje toda a água, coando, para que não perca os ovos e reserve na panela mesmo.',
  'Em uma frigideira coloque o óleo e refogue primeiramente o bacon.',
  'Deixe fritar bem até que doure a cebola e de uma corzinha ao frango.',
  'Coloque tudo na panela com o macarrão, acrescente o extrato de tomate e mexa muito bem.',
  'Já no prato, você poderá colocar o queijo ralado, ou se preferir na panela mesmo.',
  'Coloque a água do macarrão instantâneo para ferver.',
  'Enquanto isso lave bem os tomates, tire as sementes e corte em cubinhos, corte as cebolas também.',
  'Em uma frigideira doure as cebolas com um filete de azeite.',
  'Na seqüência junte os tomates e mexa um pouco',
  'Acrescente o iogurte e misture mais um pouquinho.',
  'Ponha o macarrão instantâneo para cozinhar depois de cozido escorra a água',
  'Coloque em um prato e acrescente o molho em cima do macarrão e misture até incorporar tudo.',
  'Cortei uns cubinhos de queijo prato e coloquei em cima para servir.',
  'Despejei o molho sobre a carne com legumes e deixei ferver e engrossar.',
  'Escorri o macarrão, misturei com o restante dos ingredientes e salpiquei cebolinha verde .',
  'Escorra, acrescente um pouco de manteiga e misture.',
  'Aqueça bem uma frigideira e acrescente o frango e um pouco de manteiga.',
  'Doure de um lado, acrescente um pouco mais de manteiga e doure do outro lado.',
  'Junte a cenoura cozida e o tomate e misture.',
  'Tempere com sal e pimenta. Retire do fogo, junte o manjericão e sirva em seguida.',
]